### ISSUE TITLE
Game crashes when shooting Stuka bomb the third time

### ISSUE THREAD

**Issue by taagestorey** [ianbattin/Rising#18]
Stage: 3      Step: 1      Count: 0      PlaneXY: 296.1956797016104   214.98129203335992
java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(Unknown Source)
    at Entities.Explosion.<init>(Explosion.java:105)
    at Entities.Projectile.update(Projectile.java:182)
    at Entities.Player.update(Player.java:330)
    at GameState.Boss1State.basicChecks(Boss1State.java:159)
    at GameState.Boss1State.update(Boss1State.java:108)
    at GameState.GameStateManager.update(GameStateManager.java:72)
    at Main.GamePanel.gameUpdate(GamePanel.java:160)
    at Main.GamePanel.run(GamePanel.java:105)
    at java.lang.Thread.run(Unknown Source)
java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(Unknown Source)
    at Entities.Explosion.<init>(Explosion.java:105)
    at Entities.PlaneBoss.getBulletCollision(PlaneBoss.java:837)
    at Entities.PlaneBoss.update(PlaneBoss.java:232)
    at GameState.Boss1State.basicChecks(Boss1State.java:166)
    at GameState.Boss1State.update(Boss1State.java:108)
    at GameState.GameStateManager.update(GameStateManager.java:72)
    at Main.GamePanel.gameUpdate(GamePanel.java:160)
    at Main.GamePanel.run(GamePanel.java:105)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-2" java.lang.NullPointerException
    at Entities.Explosion.<init>(Explosion.java:134)
    at Entities.PlaneBoss.getBulletCollision(PlaneBoss.java:837)
    at Entities.PlaneBoss.update(PlaneBoss.java:232)
    at GameState.Boss1State.basicChecks(Boss1State.java:166)
    at GameState.Boss1State.update(Boss1State.java:108)
    at GameState.GameStateManager.update(GameStateManager.java:72)
    at Main.GamePanel.gameUpdate(GamePanel.java:160)
    at Main.GamePanel.run(GamePanel.java:105)
    at java.lang.Thread.run(Unknown Source)

**Comment by taagestorey** [comment]
![screenshot 1683](https://cloud.githubusercontent.com/assets/15072168/15446015/c1128c7e-1ec5-11e6-84ef-d457dc520f6b.png)

**Comment by maxwey** [comment]
Does this happen every time there's an explosion? And does this happen just on the Boss fight, or does this happen when you're in level 1 too?

**Comment by taagestorey** [comment]
I've had it happen twice, but only when shooting the bomb attached to the Stuka during the fight.

**Comment by maxwey** [comment]
I had the issue as well; worked fine after cleaning the project.
